version: '2.1'
services:
  backend:
    build: FBackend
    ports:
      - "8190:8190"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/flash_learn
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    networks:
      - spring-boot-postgres
  service:
    build: FGenerationService
    container_name: generation_service
    ports:
      - "8000:8000"
    networks:
      - spring-boot-postgres
  frontend:
    build: FFrontend
    container_name: frontend_c
    ports:
      - "5174:5174"
    stdin_open: true
    tty: true
    networks:
      - spring-boot-postgres

  PostgreSQL:
    image: postgres:15.0
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=flash_learn
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-boot-postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
networks:
  spring-boot-postgres: