server:
  port: 8190
  servlet:
    context-path: /flash-learn



api:
  pexels:
    url: https://api.pexels.com/v1
    apikey: ${PROD_PEXEL_KEY}
  elevenlabs:
    url: https://api.elevenlabs.io/v1
    apikey: ${PROD_ELEVENLAB_KEY}
  deepl:
    apikey: ${PROD_DEEPL_KEY}


spring:
  application:
    name: FlashLearn
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${PROD_DP_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    hikari:
      idle-timeout: 10000
      connectionTimeout: 20000
      minimumIdle: 10
      maximumPoolSize: 20
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  security:
    enabled: true
#    enable-csrf: false