server:
  port: 8190
  servlet:
    context-path: /flash-learn

api:
  pexels:
    url: https://api.pexels.com/v1
    apikey: yourKey
  elevenlabs:
    url: https://api.elevenlabs.io/v1
    apikey: yourKey
  deepl:
    apikey: yourKey

spring:
  application:
    name: FlashLearn
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/flash_learn
    username: postgres
    password: postgres
    hikari:
      idle-timeout: 10000
      connectionTimeout: 20000
      minimumIdle: 10
      maximumPoolSize: 20
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  security:
    enabled: true
#    enable-csrf: false


